# Generated by Django 5.2.7 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('poster', models.ImageField(default='posters/default-poster.jpeg', upload_to='posters/', verbose_name='Poster')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating')),
                ('genres', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animated', 'Animated'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('romance', 'Romance'), ('sci-fi', 'Science fiction'), ('thriller', 'Thriller')], verbose_name='Genres')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('actors', models.CharField(max_length=100, verbose_name='Actors')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('status', models.CharField(choices=[('coming_out', 'Coming out'), ('finished', 'Finished'), ('coming_soon', 'Coming soon')], verbose_name='Status')),
            ],
        ),
    ]
